### ISSUE TITLE
Упаковка в исполняемые файлы с jlink и jpackage

### ISSUE THREAD

**Issue by egormkn** [Shemplo/TBS#3]
Попробовал запустить последнюю версию и получил:
```bash
$ /usr/lib/jvm/java-16-openjdk-amd64/bin/java -jar TBS-linux.jar 
Error: LinkageError occurred while loading main class ru.shemplo.tbs.RunTinkoffBondScanner
	java.lang.UnsupportedClassVersionError: ru/shemplo/tbs/RunTinkoffBondScanner has been compiled 
        by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime 
        only recognizes class file versions up to 60.0
```

Насколько я знаю, самый продвинутый способ упростить запуск до скачивания и выполнения файла без каких-либо зависимостей - использовать Java-модули и упаковывать в один исполняемый файл вместе с только используемыми модулями JRE при помощи jlink и jpackage. Я когда-то пробовал сделать такое с JavaFX, вроде работало. Будет круто, если TBS так же соберёшь

**Comment by Shemplo** [comment]
В описании же сказано, что нужна Java 17+, пока не понял, зачем мне что-то делать
