### ISSUE TITLE
Сканер зависает

### ISSUE THREAD

**Issue by sega-G14** [Shemplo/TBS#5]
После запуска сканер зависает на этапе "Dumping bonds to a binary file..."
![scan1](https://user-images.githubusercontent.com/113241423/189482214-4231b9fb-b7dc-458e-8b7f-18bd78081a28.png)

**Comment by Shemplo** [comment]
Есть подозрение, что это из-за того, что он находится в директории без прав записи. Момент, после которого происходит зависание пытается сделать именно запись на диск. Можете попробовать переместить в другую директорию, куда может писать текущий пользователь?

Если это действительно так, то добавлю какое-нибудь сообщение об ошибке в лог, чтобы было понятнее

**Comment by sega-G14** [comment]
Опишу подробнее. 
1. Программа находится в папке на рабочем столе.
2. При запуске создаю профиль и нажимаю "Scan bonds" и начинается процесс сканирования
3. В папке с программой создаются файлы emitters.bin и dump.bin. 
4. Лог сканера: Connecting to Tinkoff API...
Profile(name=S1, highResponsible=true, maxResults=0, inflation=0.011577181208053691, monthsTillEnd=2 [↥], couponsPerYear=4 [↥], daysToCoupon=10 [↥], nominalValue=1000.0 [↥], percentage=10.0 [↥], price=any, couponValuesModes=[FIXED], currencies=[RUB], creditRatings=[HIGH, MEDIUM, LOW], bannedEmitters=[])
Loading current currency quotes from Tinkoff...
Quotes: {USD=60.6, EUR=60.9675}
Loading bonds from portfolio (with data from Tinkoff and MOEX)...
Loading data about bonds from Tinkoff and MOEX...
Analizing loaded bonds (total: 0 + 8)...
Dumping bonds to a binary file...
5. На этом всё, индикатор продолжает бегать и ничего не происходит
6. Если принудительно завершить программу и запустить вновь становиться доступна кнопка "Open scanned bonds"
7. При открытии на вкладке "Scanned bonds" пусто, а на вкладке "Portfolio bonds" я вижу список своих облигаций в количестве 8 шт., о чём нам говорит запись в логе +8 (Analizing loaded bonds (total: 0 + 8)...). Следовательно что-то всё таки считывается и записывается. 
8. Немного поиграв с настройками профиля вижу, Analizing loaded bonds (total: 36 + 8)..., но всё равно процесс Dumping bonds to a binary file...длится бесконечно.

**Comment by Shemplo** [comment]
Причина понятна. Она связана с тем, что после выполнения сканирования и записи облигаций в файл `dump.bin` также ещё записывается сам лог, который представлен на скриншоте в файл `scan.log`. Из-за того, что этот файл отсутствовал возникала ошибка записи. В версии 2.4 это исправлено.

**Comment by sega-G14** [comment]
Решено. Спасибо!
