### ISSUE TITLE
Одновременное открытие одинаковых окон

### ISSUE THREAD

**Issue by sega-G14** [Shemplo/TBS#6]
На MacOS 10.15.7, при нажатии на "Scan bonds" открывается одновременно два окна сканера. При нажатии "Clone profile" одновременно появляется две копии профиля, один профиль так же не получается удалить, удаляются сразу два. 

<img width="633" alt="Снимок экрана 2022-09-14 в 18 46 39" src="https://user-images.githubusercontent.com/113241423/190172466-798b0374-effa-4e6a-8f6c-52a0b0c73aa1.png">
<img width="578" alt="Снимок экрана 2022-09-14 в 18 51 31" src="https://user-images.githubusercontent.com/113241423/190172918-8576bfaa-a10b-4377-af5e-68dfe737038c.png">

**Comment by Shemplo** [comment]
Интересный спецэффект. Мне казалось, что я его исправлял, но, видимо, нет. Посмотрю.

**Comment by Shemplo** [comment]
Исправил, попробуйте версию [2.4.1](https://github.com/Shemplo/TBS/releases/tag/2.4.1).

**Comment by sega-G14** [comment]
Исправлено
